name: 'Pull Request2'

on:
  workflow_dispatch: 

permissions: write-all

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    permissions: write-all
    environment: Dev
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changes
        env:
          GH_TOKEN: ${{ secrets.ORG_TOKEN }}
        run: |
          
          echo "laurenmnaylor" >> approvers.txt
          echo "tjzwieg" >> approvers.txt
          cat approvers.txt

          echo "laurenmnaylor" >> required_reviewers.txt
          echo "okta" >> required_reviewers.txt

          for $approver in approvers.txt 
          do
            echo "$approver"
            gh api graphql -f query='query GetTeamMembers {
              organization(login: "Eaton-Vance-Corp") {
              teams(first: 100, userLogins: [$approver]) {
                totalCount
                  edges {
                    node {
                      slug
                    }
                  }
                }
              }
         
              }' | jq '.data.organization.teams.edges[].node.slug' >> required_reviewers.txt

          done

          cat required_reviewers.txt
          
