name: 'Pull Request2'

on:
  workflow_dispatch: 

permissions: write-all

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    permissions: write-all
    environment: Dev
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changes
        env:
          GH_TOKEN: ${{ secrets.ORG_TOKEN }}
        run: |
          
          
          gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /orgs/Eaton-Vance-Corp/teams
          
