name: 'Pull Request'

on:
  pull_request:
  pull_request_review:
    types: [submitted]

jobs:       
  changedfiles:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changes
        env:
          GH_TOKEN: ${{ secrets.ORG_TOKEN }}
        run: |
          git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} >> diffs.txt 
          echo "DIFFS.TXT"
          cat diffs.txt
       
          cat .github/CODEOWNERS-custom | while read line
          do
            echo $line >> codeowners.txt
          done
          echo "CODEOWNERS.TXT"
          cat codeowners.txt

          if ! grep -f diffs.txt codeowners.txt | grep -o "@\S*" >> required_reviewers.txt; then
            echo "No matches" >> required_reviewers.txt
          fi
          sed 's/@//' required_reviewers.txt
          echo "REQUIRED_REVIEWERS.TXT"  
          cat required_reviewers.txt
          
          reviews=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/laurenmnaylor/terraform-okta-test/pulls/${{ github.event.pull_request.number }}/reviews)
          echo "$reviews" | jq 'sort_by(.user.login, .submitted_at) | reverse | unique_by(.user.login) | map(select(.state=="APPROVED")) | .[].user.login' >> approvers.txt
          echo "APPROVERS.TXT"
          cat approvers.txt

          
          echo "RUNNING COMM"
          comm -13 <(sort -u approvers.txt) <(sort -u required_reviewers.txt)

          

          
