name: 'Pull Request'

on:
  pull_request:
  pull_request_review:
    types: [submitted]

permissions: write-all

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Set outputs using the command.
        run: |
          echo "v=${{ github.event.pull_request.number }}"
          echo $v
          diffs=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "all=$((git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}) | xargs)" >> $GITHUB_OUTPUT
          #echo "all=$(cat .github/CODEOWNERS-custom)" >> $GITHUB_OUTPUT
          #echo $all
          expanded=""
          cat .github/CODEOWNERS-custom | while read line
          do
            echo $line >> tmp.txt
          done
          cat tmp.txt
          
          reviews=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/laurenmnaylor/terraform-okta-test/pulls/${{ github.event.pull_request.number }}/reviews)
          echo $reviews
          echo "$reviews" | jq 'map(select(.state=="APPROVED"))'
          echo "users=$($reviews | jq '.[].user.login')"
          echo "states=$($reviews | jq '.[].state')"
          echo $users
          echo $states

          for item in $diffs; do
            echo $item
          done
          rm tmp.txt
         
          
  lint:
    runs-on: ubuntu-latest
    # require the first job to have ran
    needs: changedfiles
    # only run there are changed files
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: echo changed files
        run: |
          echo ${{needs.changedfiles.outputs.all}}
          for item in ${{needs.changedfiles.outputs.all}}; do
            echo "$item"
          done
