name: 'Run Script'

on:
  workflow_dispatch:

jobs:
  generate-jwt:
    runs-on: ubuntu-latest
    permissions: write-all
    environment: 'generate jwt'
    env:
      GH_TOKEN: ${{ secrets.ORG_TOKEN }}
    outputs:
      jwt: ${{ steps.generate-jwt.outputs.jwt }}
    steps:
      # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get changed files
        id: generate-jwt
        run: |
          cd js
          npm init -y
          npm install
          npm i njwt
          npm ci
          token=$(node generate-jwt.js "${{ secrets.TF_VAR_private_key }}" "0oah96zm3mSlrHKV05d7" "dev-86564089.okta.com")
          echo $token >> token.txt
          cat token.txt
          gh secret set JWT_TOKEN -b $token
          echo "jwt=$(echo $token | base64 -w0 | base64 -w0)" >> $GITHUB_OUTPUT
          
  deploy:
    name: 'Get Okta Resource ID'
    environment: 'generate jwt'
    runs-on: ubuntu-latest
    needs: [ generate-jwt ]
    steps:
      - name: Get Resource ID
        run: |
          
          jwt=${{ needs.generate-jwt.outputs.jwt }}
          jwt=$(echo $jwt | sed 's/=.*//g')
          jwt=$(echo ${jwt#*=} | base64 -di | base64 -di)
          echo "JWT"
          echo $token
          
          cat > curl_access_token.sh
          chmod +x curl_access_token.sh
          echo "curl --location --request POST 'https://dev-86564089.okta.com/oauth2/v1/token' --header 'Accept: application/json' --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'grant_type=client_credentials' --data-urlencode 'scope=okta.apps.read' --data-urlencode 'client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer' --data-urlencode 'client_assertion=${{ secrets.JWT_TOKEN }}'" > curl_access_token.sh
          accessToken=$(./curl_access_token.sh | jq -r '.access_token')
          
          declare okta_url="https://dev-86564089.okta.com/api/v1"
          declare result=""
          declare url=""
          declare jq_filter=""
          
          url="$okta_url/apps"
          jq_filter="jq"
          
          
          cat > curl2.sh
          chmod +x curl2.sh
          
          echo "curl -s -D headers.txt -X GET -H \"Accept: application/json\" -H \"Content-Type: application/json\" -H \"Authorization: Bearer $accessToken\" \"${url}\" | jq 'map({name: .label, id: .id})'" > curl2.sh
          cat curl2.sh
          ./curl2.sh >> results.txt
          cat results.txt