name: 'Run Script'

on:
  workflow_dispatch:

jobs:
  generate-jwt:
    runs-on: ubuntu-latest
    permissions: write-all
    environment: 'generate jwt'
    env:
      GH_TOKEN: ${{ secrets.ORG_TOKEN }}
    outputs:
      jwt: ${{ steps.generate-jwt.outputs.jwt }}
    steps:
      # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get changed files
        id: generate-jwt
        run: |
          cd js
          npm init -y
          npm install
          npm i njwt
          npm ci
          token=$(node generate-jwt.js "${{ secrets.TF_VAR_private_key }}" "0oah96zm3mSlrHKV05d7" "dev-86564089.okta.com")
          echo $token >> token.txt
          cat token.txt
          echo "jwt=$(echo $token | base64 -w0 | base64 -w0)" >> $GITHUB_OUTPUT
  
          
          
          cat > curl_access_token.sh
          chmod +x curl_access_token.sh
          echo "curl --location --request POST 'https://dev-86564089.okta.com/oauth2/v1/token' --header 'Accept: application/json' --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'grant_type=client_credentials' --data-urlencode 'scope=okta.apps.read' --data-urlencode 'client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer' --data-urlencode 'client_assertion=$token'" > curl_access_token.sh
          accessToken=$(./curl_access_token.sh | jq -r '.access_token')
          at=$(echo $accessToken | base64 -w0 | base64 -w0)
          echo "ACCESS TOKEN"
          echo $at
          
         