name: 'Run Script'

on:
  workflow_dispatch:

jobs:
  generate-jwt:
    runs-on: ubuntu-latest
    permissions: write-all
    environment: 'generate jwt'
    steps:
      # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get changed files
        id: generate-jwt
        run: |
          cd js
          npm init -y

          
          declare okta_url="https://dev-86564089.okta.com/api/v1"
          declare result=""
          declare url=""
          declare jq_filter=""
          
          url="$okta_url/apps"
          jq_filter="jq"
          
          
          cat > curl2.sh
          chmod +x curl2.sh
          
          echo "curl -s -D headers.txt -X GET -H \"Accept: application/json\" -H \"Content-Type: application/json\" -H \"Authorization: SSWS ${{ secrets.TF_VAR_api_key }}\" \"${url}\"" > curl2.sh
          cat curl2.sh
          ./curl2.sh >> results.txt
          cat results.txt