name: 'Terraform'

on:
  workflow_dispatch:


permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: Personal-Test
    

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Terraform Init
      run: terraform init
    - name: Terraform Plan
      env:
        TF_VAR_org_name: ${{ vars.TF_VAR_org_name }}
        TF_VAR_base_url: ${{ vars.TF_VAR_base_url }}
        TF_VAR_api_token: ${{ secrets.TF_VAR_api_token }}
        TF_VAR_env: 'personal-test'
      run: |
        terraform plan -input=false
    - name: Terraform Apply
      env:
        TF_VAR_org_name: ${{ vars.TF_VAR_org_name }}
        TF_VAR_base_url: ${{ vars.TF_VAR_base_url }}
        TF_VAR_api_token: ${{ secrets.TF_VAR_api_token }}
        TF_VAR_env: 'personal-test'
      run: |
        terraform apply -auto-approve -input=false
